
# cloudbuild.yaml
steps:
  # Step 1: Get git commit count and set as environment variable
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git fetch --unshallow || true # Fetch full history. "|| true" prevents failure if not a shallow clone.
        commit_count=$(git rev-list --count HEAD)
        echo "Commit count: $commit_count"
        echo "$commit_count" > /workspace/commit_count.txt

  # Step 2: Build the Docker image with commit count
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_COMMIT_COUNT=$(cat /workspace/commit_count.txt)'
      - '-t'
      - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/langcanvas-repo/langcanvas-app:${COMMIT_SHA}' # Updated region for Artifact Registry
      - '-t'
      - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/langcanvas-repo/langcanvas-app:latest' # Updated region for Artifact Registry
      - '.'

  # Step 3: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/langcanvas-repo/langcanvas-app:${COMMIT_SHA}' # Updated region for Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/langcanvas-repo/langcanvas-app:latest' # Updated region for Artifact Registry

  # Step 4: Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'langcanvas-app' # Name of your Cloud Run service
      - '--image'
      - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/langcanvas-repo/langcanvas-app:${COMMIT_SHA}' # Updated region for Artifact Registry
      - '--region'
      - 'europe-west4' # Updated Cloud Run region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=8080'
    entrypoint: gcloud

options:
  logging: CLOUD_LOGGING_ONLY
